name: Publish PowerShell Module
on: [push]
#  release:
#    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          echo "The current path is: $($pwd.path)"
          Get-ChildItem -Recurse | Select-Object -Expand FullName
          #Publish-Module -Path "GATestingModule/GATestingModule.psd1" -NuGetApiKey $env:NUGET_KEY -Verbose

#Publish-Module -Path /tmp/samplemodule -NuGetApiKey $env:NUGET_KEY -Verbose
