name: Publish PowerShell Module
on:
  push:
    branches:
      - "main"

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          echo "The current path is: $($pwd.path)"
          echo "Building..."
          ./build.ps1 -Path /${{ github.event.repository.name }}
          echo ""
          echo "Listing files:"
          Get-ChildItem -Recurse
          echo ""
          echo "Publishing..."
          Publish-Module -Path "./${{ github.event.repository.name }}/" -NuGetApiKey $env:NUGET_KEY -Verbose

#Publish-Module -Path /tmp/samplemodule -NuGetApiKey $env:NUGET_KEY -Verbose
