name: Publish PowerShell Module
on:
  push:
    branches:
      - "main"

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Publish PowerShell Module
        uses: natescherer/publish-powershell-action@v1
        with:
          token: ${{ secrets.NUGET_KEY }}
          target: gallery
          path: Source
